### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by hollandjg** [AutoResearch/autora#102]
Badges should include:
- conda (version)
- pypi (version)
- tests (passing or failing – needs #103 )

**Comment by hollandjg** [comment]
Needs input:
@musslick which badges do we want / need? Some are implemented already (see https://github.com/AutoResearch/autora)

**Comment by musslick** [comment]
@hollandjg 
Thanks for checking. I would add 

- [ ] a license badge (soon to be changed to MIT license). 

If it is also possible to add hyperlinks to these badges, then I would add:
- [ ] a custom badge [Doc | autoresearch.github.io] with link to the documentation
- [ ] a custom badge [Forum | Github Discussions] with link to Github Discussions
