### ISSUE TITLE
Fix conda build command

### ISSUE THREAD

**Issue by benwandrew** [AutoResearch/autora#139]
Running the `publish-on-anaconda-org.sh` on anaconda leads to error. 

` RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)`

**Comment by hollandjg** [comment]
Seen on StackOverflow
https://stackoverflow.com/questions/73876790/poetry-configuration-is-invalid-additional-properties-are-not-allowed-group

**Comment by benwandrew** [comment]
seems like people have found a workaround using `conda mambabuild` via [boa](https://boa-build.readthedocs.io/en/latest/)?

on the other hand, others point to python 3.10 being the crux of the issue: https://github.com/rdkit/rdkit/discussions/5590#discussioncomment-3734800

**Comment by benwandrew** [comment]
actually, i'm not sure either of ^those are relevant
