### ISSUE TITLE
make latex and model output the same across DARTS and BMS regressors

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#193]
For now, DARTS and BMS regressors use different functions for returning a latex version of the model or a string version of the model. We should refactor so they use the same functions.

**Comment by benwandrew** [comment]
should this entail creating a common `utils.py` for all theorists? also, just for clarification, this refers to the `model_repr` method for DARTS (https://github.com/AutoResearch/autora/blob/59116582b1eedf141cce0dcb7611b3d3c1c4f17a/autora/skl/darts.py#L731) and the `present_results` method for BMS (https://github.com/AutoResearch/autora/blob/59116582b1eedf141cce0dcb7611b3d3c1c4f17a/autora/theorist/bms/utils.py#L44), correct?
