### ISSUE TITLE
fix: types of Pool and Pipe

### ISSUE THREAD

**Issue by hollandjg** [AutoResearch/autora#197]
remove ignore comments from [example/cycle/simple_cycle_bms_model_poppernet.py](https://github.com/AutoResearch/autora/issues/new#diff-05d1ba9c884167c783cff1ac561e09edd533fc145efcf43b5cd1a3c0e9df72b6) lines 50, 51, 88, 89

**Comment by benwandrew** [comment]
is this still relevant?

**Comment by hollandjg** [comment]
Superseded by https://github.com/AutoResearch/autora-core/pull/33
