### ISSUE TITLE
chore: Handover maintenance responsibility from CCV to AER Group

### ISSUE THREAD

**Issue by hollandjg** [AutoResearch/autora#249]
- [ ] PRs / issues
  - [ ] PR and issue Management in general (creating PRs and issues, closing PRs and issues, set up regular process to keep up to date)
  - [ ] how are PRs organized? Chained PRs? When do you consider PRs done and ready to merge into main? Do changes after a merge require a new PR?
  - [x] Dealing with merging / rebasing / branches
- [x] Dependabot (process, discuss desired frequency and set up, support group)
- [x] Setting up and repairing venv environments
- [x] Publishing #257 
  - [x] PyPI
  - [ ] Conda
- [x] Handling code contributions for experimentalists & theorists – what should people submit in their PRs?
- [x] Philosophy of dependencies – do we want to limit dependencies? What about conflicting dependencies?
- [ ] Design principles? What and how to test? What is pythonic? What is a good interface? Functions vs classes? 
  - [ ] Code coverage and checking that you've covered all the bases in tests, avoiding breakages
- [ ] Automation
  - [x] Github Actions
  - [ ] How to update pre-commit hooks? Change them? Remove them?

**Comment by hollandjg** [comment]
The easiest way to handle publishing is to automate it using GitHub actions. So that's what we'll do.

**Comment by gtdang** [comment]
Notes from Apr 4 Meeting: 
1. Philosophy on dependencies. 
2. When a new PR/feature is added with additional or conflicting dependencies, what do we do? 
3. Design principles. * What is Pythonic? Control structures? Class vs functional paradigm? 
4. How to update pre-commit hooks? Change? Remove? Update?

**Comment by hollandjg** [comment]
We declared this as done on Tuesday August 15th
