### ISSUE TITLE
enable search through our documentation

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#467]
Users should be able to search through the .md files in our documentation. Perhaps we can use this plugin:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/

**Comment by hollandjg** [comment]
Already done:
![Screenshot 2023-06-20 at 10 53 42](https://github.com/AutoResearch/autora/assets/2803227/860e313f-3f22-417a-900f-8924c9516faf)

Anything else we need to do here, @musslick ?
