### ISSUE TITLE
Make explicit certain subtleties to using autoRA experimentalist and cycle

### ISSUE THREAD

**Issue by TheLemonPig** [AutoResearch/autora#511]
E.g.
When making an experimentalist, you must pass a fit theorist. When making a cycle, you do not need to fit the theorist.
When using an experimentalist, you do not need to package it into a pipeline. When making a cycle, you must packaged it.

In both cases, the implied additional issue is having to input the theorist in two places to run the autora cycle.

**Comment by musslick** [comment]
This will no longer be necessary due to refactoring of cycle.
