### ISSUE TITLE
Standardize repository issue labels with Label Syncer

### ISSUE THREAD

**Issue by gtdang** [AutoResearch/autora#530]
Implement label syncer to sync labels across repos. 
https://github.com/marketplace/actions/label-syncer

- [x] Create config file with standard labels 
- [x] Create GitHub Action to standardize labels across appropriate repositories 
- [ ] #536

**Comment by benwandrew** [comment]
regarding the last point, i'm happy to assume responsibility for updating and running the action when a new repo is created, but i'm not sure of the best way of being notified. i just enabled this

<img width="338" alt="Screen Shot 2023-07-27 at 10 29 02" src="https://github.com/AutoResearch/autora/assets/28738595/122cd704-34ea-422d-9bf1-1eb815f4b912">

although i didn't get an email when i created a couple test repos just now. @gtdang @younesStrittmatter can either of you try creating a dummy repo? alternatively, do you have any better ideas for streamlining the process of updating and running the new action? i haven't (at least yet) found a satisfactory way to automate. @gtdang, what did you mean by creating another action?

**Comment by gtdang** [comment]
@benwandrew  I just created [dummy-repo-test](https://github.com/AutoResearch/dummy-repo-test)

**Comment by benwandrew** [comment]
> @benwandrew I just created [dummy-repo-test](https://github.com/AutoResearch/dummy-repo-test)

awesome, it worked — i got a notification via email!

**Comment by gtdang** [comment]
I think we can merge your existing PR and create a new issue for the last point as a nice to have. For now the manual method will suffice?
