### ISSUE TITLE
update license to MIT

### ISSUE THREAD

**Issue by hollandjg** [AutoResearch/autora#533]
Note: to make the license badge work as we want it to, we need to update the parent package license to MIT and re-release.

_Originally posted by @hollandjg in https://github.com/AutoResearch/autora/issues/532#issuecomment-1653920537_

**Comment by musslick** [comment]
@benwandrew @chadcwilliams Would either of you be open to taking this on? Happy to discuss this!

**Comment by benwandrew** [comment]
> @benwandrew @chadcwilliams Would either of you be open to taking this on? Happy to discuss this!

you bet! new PR here: https://github.com/AutoResearch/autora/pull/537
