### ISSUE TITLE
update dependencies based on new packages (post hackathon)

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#544]
This will require dependency updating in autora (as a last step).

**Comment by benwandrew** [comment]
happy to spearhead this, but not totally sure of everything that needs to be done (sorry, still playing catch-up!). i see a new version of the mixture experimentalist that will need to be updated in the parent (1.0.0a4 —> 1.0.0a7,) as well as some altogether new repos. can i chat with someone live early next week to clarify and/or can someone add a bulleted checklist of requirements to this issue? thanks!
