### ISSUE TITLE
reach out to OSF to inquire about using their database for closed-loop experiments

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#553]

**Comment by benwandrew** [comment]
@younesStrittmatter @musslick, just heard back from Nici at OSF:

"The short answer is yes, the OSF supports this use case and we are supportive of the use of OSF for this type of workflow. It would be good to talk through the details to help support the RA, and also use it to potentially write up the use case for others to understand and benefit. Could we find a time in the next couple of weeks?

Not sure if this would be useful, we have a page that lists the open source tools developed to work with the OSF API for various research workflows [here](https://www.cos.io/communities/software-developers). The [OSFclient ](https://github.com/osfclient/osfclient)sounds like the workflow tool the RA might be able to use, and there are others there to explore for potentially other needs."

**Comment by younesStrittmatter** [comment]
For me, the earlier the better so 10/10 would be the best, but 10/6, 10/9 and 10/13 also work.

**Comment by benwandrew** [comment]
sorry @younesStrittmatter, 10/9 at 2pm ET was the only time @musslick could make!

**Comment by musslick** [comment]
It seems @younesStrittmatter did that already.
