### ISSUE TITLE
ci: Make pre-commit hooks run on PR in core packages

### ISSUE THREAD

**Issue by benwandrew** [AutoResearch/autora#565]
Make pre-commit hooks run in "core" packages on PR, for example, in autora-synthetic. Use the example in https://github.com/AutoResearch/autora-core to do this.

**Comment by benwandrew** [comment]
this is going to be an effort that involves everyone since i just don't have the familiarity with individual modules to fix all errors after running the hooks... i have spent a decent amount of time spinning my wheels here without progress. perhaps the author of each module can add and run the hooks, and then resolve the resulting errors for their own modules?

**Comment by musslick** [comment]
- [ ] remove mypy from core packages except ones where it already passes
- [ ] for each package where mypy was remove, add an issue to add it back

**Comment by younesStrittmatter** [comment]
[ ] https://github.com/AutoResearch/autora-experimentalist-novelty 
[ ] https://github.com/AutoResearch/autora-theorist-darts 
[ ] https://github.com/AutoResearch/autora-theorist-bsr
[ ] https://github.com/AutoResearch/autora-theorist-bms
[ ] https://github.com/AutoResearch/autora-experimentalist-model-disagreement
[ ] https://github.com/AutoResearch/autora-experimentalist-uncertainty
[ ] https://github.com/AutoResearch/autora-experimentalist-nearest-value
[ ] https://github.com/AutoResearch/autora-experimentalist-leverage
[ ] https://github.com/AutoResearch/autora-experimentalist-inequality
[ ] https://github.com/AutoResearch/autora-experimentalist-assumption
[ ] https://github.com/AutoResearch/autora-experimentalist-falsification
[ ] https://github.com/AutoResearch/autora-synthetic-psychology-ssm
[ ] https://github.com/AutoResearch/autora-synthetic-abstract-equation
