### ISSUE TITLE
release experimentalists

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#573]
Just make sure all the latest versions of experimentalists are released.

@chadcwilliams:
- [x] falsification
- [x] novelty
- [x] model diagreement
- [x] leverage
- [x] inequality
- [x] nearest value
- [x] uncertainty
<del> - [ ] mixture </del>
- [x] assumption

_Note: Mixture experimentalist is not currently an autora repo and in dev, so skipped_

**Comment by chadcwilliams** [comment]
Completed! 

Note: Mixture experimentalist is not currently an autora repo and in dev, so skipped
