### ISSUE TITLE
Document Workflow Logic

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#597]
Include general documentation about state logic

- [x] Depends on https://github.com/AutoResearch/autora-core/issues/65
- [x] There also needs to be a general start point about the introduction: https://github.com/AutoResearch/autora-core/pull/68

**Comment by hollandjg** [comment]
I've added some additional user guide pieces on the CLI in #612 (and associated PRs in the autora-core repo).

**Comment by hollandjg** [comment]
Done!
