### ISSUE TITLE
Experiment Manager vs. Runner in Documentation

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#663]
It is not quite clear how "Experiment Managers" are different from Experiment Runners. 
We should add an ``index.md`` to the Experiment Managers section in the doc to explain what they are, and how they are related to experiment runners.

**Comment by younesStrittmatter** [comment]
I think we should drop the distinction to make it less complex. The only "weird" thing is a prolific recruiter is not really a runner and would still be in the runner section
