### ISSUE TITLE
Orphan closed-loop example

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#664]
There is apparently a closed-loop example that somewhere exists in the AutoRA documentation. I stumbled upon it by searching for "firebase_runner". 

This is the link:
https://autoresearch.github.io/autora/user-cookiecutter/docs/examples/Mathematical%20Model%20Discovery/

I think we should find it, rework it, and place it somewhere visible (e.g., under examples). Currently, it's nowhere to be found in the cookie cutter documentation.

**Comment by younesStrittmatter** [comment]
There are two cookiecutter templates: one for contributor and one for users. This is in the user template. But the user template doesn't have it's own documentation (which it should or should not have, I am not sure)
